In [1]:
import numpy as np
import pandas as pd

In [4]:
# -> array multidimensional usando lista de listas

multidimensional_array = np.array([range(i, i+3) for i in [2, 4, 6]])
display(multidimensional_array)

# array([[2, 3, 4],
#        [4, 5, 6],
#        [6, 7, 8]])
# linhas internas tratadas como linhas de um array
# bidimensional resultante

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
# create an array of integers with lenght = 10 and field with 0

zero_arr = np.zeros(10, dtype=int)
display(zero_arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# array with only one values, 3x5 lenght

one_arr = np.ones((3, 5), dtype=int)
display(one_arr)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
# create a full array with value = 3.14

full_array = np.full((3, 5), 3.14)
display(full_array)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# like the range func, create an array with a linear sequence

range_arr = np.arange(0, 20, 2)
display(range_arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# array equal spaced in a determined range

equal_arr = np.linspace(0, 1, 5, dtype=float)
display(equal_arr)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
# random array between 0 and 1 

r_arr = np.random.random((3, 3))  # pass through only one argument
display(r_arr)

array([[0.36425066, 0.94976063, 0.11887073],
       [0.24848314, 0.91373507, 0.6692899 ],
       [0.04335495, 0.61872739, 0.43994005]])

In [24]:
# create a random array with means and standard deviation

mat_arr = np.random.normal(0, 1, (3,3)) 
# mean = 0
# standart deviation = 1 (*desvio padrao)

display(mat_arr)

array([[-1.58847553, -0.32542596,  0.59024957],
       [-0.25354534, -1.50863823, -1.34788897],
       [ 0.40988856,  1.06861923, -1.90201547]])

In [25]:
# create a random array with random numbers

random_arr = np.random.randint(0, 10, (3, 3))

display(random_arr)

array([[3, 5, 8],
       [5, 4, 2],
       [5, 6, 4]])

In [27]:
# create an indentity matriz

matrix_arr = np.eye(3)
display(matrix_arr)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# create a not innitializated array with numbers in that memory allocation

empty_arr = np.empty(3)
display(empty_arr)

array([1., 1., 1.])