In [3]:
import pandas as pd
import numpy as np

In [ ]:
rng = np.random.default_rng(seed=1701)  # cria gerador de numeros aleatorios de mesma seed

x1 = rng.integers(low=0, high=10, size=6)

display(x1.ndim)  # 1
display(x1.size)  # 6
display(x1.shape)  # (6, )
display(x1.dtype)  # int64

1

6

(6,)

dtype('int64')

In [ ]:
x2 = rng.integers(10, size=(3,4))

display(x2)
display(x2[2, 0])  # -> 2

array([[4, 3, 5, 5],
       [0, 8, 3, 5],
       [2, 2, 1, 8]])

np.int64(2)

In [ ]:
display(x1)  # array([9, 4, 0, 3, 8, 6])
display(x1[::2])  # [9,0,8]
display(x1[4::-2])  # array([8, 0, 9])


array([9, 4, 0, 3, 8, 6])

array([9, 0, 8])

array([8, 0, 9])

In [ ]:
display(x2)

# array([[4, 3, 5, 5],
#        [0, 8, 3, 5],
#        [2, 2, 1, 8]])

display(x2[::2, ::3])

# array([[4, 5],
#        [2, 8]])

display(x2[::-1, ::-1])

# array([[8, 1, 2, 2],
#        [5, 3, 8, 0],
#        [5, 5, 3, 4]])

array([[4, 3, 5, 5],
       [0, 8, 3, 5],
       [2, 2, 1, 8]])

array([[4, 5],
       [2, 8]])

array([[8, 1, 2, 2],
       [5, 3, 8, 0],
       [5, 5, 3, 4]])

In [ ]:
# copiar subarrays: 

x2_subcopy = x2[:2, :2].copy()
display(x2_subcopy)

# array([[4, 3]
#        [0, 8]])

x2_subcopy[0, 0] = 42
display(x2_subcopy)

# array([[42,  3],
#        [ 0,  8]])

array([[4, 3],
       [0, 8]])

array([[42,  3],
       [ 0,  8]])

In [ ]:
# remodelacao de arrays: 

x = np.array([(1, 2, 3)])
display(x)

grid = np.arange(1, 10).reshape(3, 3)
display(grid)

display(x.reshape(3, 1))  # inverte colunas e linhas

display(x[np.newaxis, :])  # array([[[1, 2, 3]]])



array([[1, 2, 3]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1],
       [2],
       [3]])

array([[[1, 2, 3]]])

In [33]:
# concatenacao de arrays: 

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([99, 99, 99])

print(np.concatenate([x, y, z]))  # [ 1  2  3  4  5  6 99 99 99]

grid = np.array(
    [[1, 2, 3],
    [4, 5 ,6]]
)
display(np.concatenate([grid, grid]))
# array([[1, 2, 3],
#        [4, 5, 6],
#        [1, 2, 3],
#        [4, 5, 6]])

display(np.concatenate([grid, grid], axis=1))
# array([[1, 2, 3, 1, 2, 3],
#        [4, 5, 6, 4, 5, 6]])

y = np.array([
    [99],
    [99]
])

display(np.hstack([grid, y]))
# array([[ 1,  2,  3, 99],
#        [ 4,  5,  6, 99]])

display(np.vstack([x, grid]))

[ 1  2  3  4  5  6 99 99 99]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
# separacao de arrays

x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x1, x2, x3 = np.split(x, [3, 5])

grid = np.arange(16).reshape((4, 4))

upper, lower = np.vsplit(grid, [2])
left, right = np.hsplit(grid, [2])

display(x1)
display(x2)
display(x3)
display(upper)
display(lower)
display(left)
display(right)


array([1, 2, 3])

array([99, 99])

array([3, 2, 1])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])